import type { Metadata } from 'next';

import { Geist, Geist_Mono } from 'next/font/google';

import '@/app/globals.css';
import React from 'react';

const geistSans = Geist({
  // eslint-disable-next-line @stylistic/quotes
  subsets: ['latin'],
  // eslint-disable-next-line @stylistic/quotes
  variable: '--font-geist-sans',
});

const geistMono = Geist_Mono({
  // eslint-disable-next-line @stylistic/quotes
  subsets: ['latin'],
  // eslint-disable-next-line @stylistic/quotes
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  description: `Generated by create next app`,
  title: `Create Next App`,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
