import type { Metadata } from 'next';

import '@/styles/globals.css';
import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';
import React from 'react';

const geistSans = Geist({
  // eslint-disable-next-line @stylistic/quotes
  subsets: ['latin'],
  // eslint-disable-next-line @stylistic/quotes
  variable: '--font-geist-sans',
});

const geistMono = Geist_Mono({
  // eslint-disable-next-line @stylistic/quotes
  subsets: ['latin'],
  // eslint-disable-next-line @stylistic/quotes
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  description: `Generated by create next app`,
  title: `CS 321 Grocery List`,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col gap-4 antialiased`}
      >
        <header className='flex border-b px-16 py-4'>
          <Link
            className='text-2xl font-semibold hover:text-black'
            href='/dashboard'
          >
            Grocery List
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
